### ISSUE TITLE
используется только один параметр из трех!

### ISSUE THREAD

**Issue by paladinbbk** [kmorenov/mvc_km#3]
https://github.com/kmorenov/mvc_km/blob/831ebb19dddc592b2f7ffaaf0580869dacf8d8fe/src/Controller/AbstractController.php#L11

**Comment by kmorenov** [comment]
Это не совсем понятно. Параметры используются дальше во view. 
$this->render('views/index.php', $arr, $vh); передает 3 параметра
$this->render('views/edit_post.php', $post); передает 2 параметра
$this->render('views/404.php', null); передает 1 параметр

**Comment by paladinbbk** [comment]
ясно я не проверял во вью. понятнее когда это все в один массив собирается и потом уже по переменным разбивается. а то параметры использовать в инклуде немного странно

**Comment by kmorenov** [comment]
ViewHelper метод сделал статическим, вызываемым из view. $template и данные собрал в массив.

**Comment by kmorenov** [comment]
ViewHelper метод сделал статическим, вызываемым из view. $template и данные **разделены**
