### ISSUE TITLE
много конкатенация.  идея отделения вьюхи в том что ее сможет поправить верстальщик. но здесь все на чистом php. нужно использовать для вывода html закрывающий тег php 

### ISSUE THREAD

**Issue by paladinbbk** [kmorenov/mvc_km#6]
https://github.com/kmorenov/mvc_km/blob/831ebb19dddc592b2f7ffaaf0580869dacf8d8fe/views/index.php#L12

**Comment by kmorenov** [comment]
переписал согласно идее отделепия view для удобства верстальщика
