### ISSUE TITLE
зачем к данным подсовывать темплейт. это разные переменные

### ISSUE THREAD

**Issue by paladinbbk** [kmorenov/mvc_km#8]
https://github.com/kmorenov/mvc_km/blob/acf467ad522f8654379d50f7eec40eabf9afae50/src/Controller/MainController.php#L16

**Comment by kmorenov** [comment]
Вы писали в #3: "понятнее когда это все в один массив собирается и потом уже по переменным разбивается. а то параметры использовать в инклуде немного странно"

**Comment by paladinbbk** [comment]
да согласен запутал. Все переменные с данными для темплейта в один массив. но сам темплейт и все что не является данными  должно быть выделено.

**Comment by kmorenov** [comment]
вернул на пол-шага назад: темплейт и дата разделены
